#!/usr/bin/env bash
# ===========================================================================
# pi-sync.sh — Bootstrap pi settings, themes, and packages to a new device.
#
# INTENDED AUDIENCE: This script is written for an LLM (or a human) to read
# and execute. Every step is documented inline. The LLM should read the
# comments, understand the topology, and run the relevant commands on each
# machine (source = old device with config, target = new device).
#
# TOPOLOGY:
#   source     = the device with existing ~/.pi/agent/ config (this Pixel 6a)
#   target     = the new device you want to replicate config TO
#
# USAGE:
#   Phase 1 — Run on SOURCE to package config:
#     ./scripts/pi-sync.sh export
#
#   Phase 2 — Copy the tarball to the target (scp, USB, cloud, whatever)
#
#   Phase 3 — Run on TARGET to unpack and install:
#     ./scripts/pi-sync.sh import <path-to-tarball>
#
# WHAT IT SYNCS:
#   ✅  ~/.pi/agent/settings.json    — theme, provider, model, packages list
#   ✅  ~/.pi/agent/themes/*.json    — custom themes (lotek, etc.)
#   ✅  package list from settings   — re-installed via `pi install`
#   ❌  auth.json                    — API keys stay local to each device
#   ❌  chat sessions / history      — local only
#   ❌  models-store.json            — auto-regenerated by pi
#   ❌  node_modules / git repos     — re-cloned by `pi install`
# ===========================================================================
set -euo pipefail

PI_AGENT_DIR="${HOME}/.pi/agent"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
EXPORT_DIR="${SCRIPT_DIR}/pi-config-export"

# ── Colors for pretty output ──────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info()  { echo -e "${CYAN}✦${NC} $1"; }
ok()    { echo -e "${GREEN}✓${NC} $1"; }
warn()  { echo -e "${YELLOW}⚠${NC} $1"; }
err()   { echo -e "${RED}✗${NC} $1"; }

# ===========================================================================
# PHASE 1 — EXPORT (run on the SOURCE device)
#
# Packs the following into a portable directory:
#   - settings.json       (full pi config)
#   - themes/*.json       (all custom themes)
#   - packages.txt        (list of installed pi packages, extracted from settings)
#
# The output goes to scripts/pi-config-export/ and is then tarballed.
# ===========================================================================
do_export() {
    echo ""
    info "╔══════════════════════════════════════════════════════════════╗"
    info "║  pi-sync: EXPORT phase — run this on the SOURCE device     ║"
    info "╚══════════════════════════════════════════════════════════════╝"
    echo ""

    # -- Validate that pi's agent dir exists --------------------------------
    if [ ! -d "${PI_AGENT_DIR}" ]; then
        err "~/.pi/agent/ not found at ${PI_AGENT_DIR}"
        err "Is pi installed on this machine?"
        exit 1
    fi
    ok "Found ~/.pi/agent/ at ${PI_AGENT_DIR}"

    # -- Create export directory (fresh each time) --------------------------
    rm -rf "${EXPORT_DIR}"
    mkdir -p "${EXPORT_DIR}/themes"
    ok "Created export directory: ${EXPORT_DIR}"

    # -- Export settings.json -----------------------------------------------
    if [ -f "${PI_AGENT_DIR}/settings.json" ]; then
        cp "${PI_AGENT_DIR}/settings.json" "${EXPORT_DIR}/settings.json"
        ok "Exported settings.json"
    else
        warn "No settings.json found — skipping"
    fi

    # -- Export themes ------------------------------------------------------
    if [ -d "${PI_AGENT_DIR}/themes" ] && [ "$(ls -A "${PI_AGENT_DIR}/themes" 2>/dev/null)" ]; then
        cp "${PI_AGENT_DIR}/themes/"*.json "${EXPORT_DIR}/themes/"
        ok "Exported $(ls "${PI_AGENT_DIR}/themes/"*.json 2>/dev/null | wc -l) theme(s):"
        for f in "${PI_AGENT_DIR}/themes/"*.json; do
            echo "      $(basename "$f")"
        done
    else
        warn "No custom themes found — skipping"
    fi

    # -- Extract package list from settings.json ----------------------------
    if [ -f "${PI_AGENT_DIR}/settings.json" ]; then
        # Use Node.js to reliably parse JSON and extract the packages array
        node -e "
            const s = require('${PI_AGENT_DIR}/settings.json');
            const pkgs = s.packages || [];
            if (pkgs.length === 0) process.exit(1);
            console.log(pkgs.join('\n'));
        " > "${EXPORT_DIR}/packages.txt" 2>/dev/null && {
            ok "Exported $(wc -l < "${EXPORT_DIR}/packages.txt") package(s) to packages.txt"
            cat "${EXPORT_DIR}/packages.txt" | sed 's/^/      /'
        } || {
            warn "No packages found in settings.json or Node.js unavailable"
            touch "${EXPORT_DIR}/packages.txt"
        }
    fi

    # -- Tarball it ---------------------------------------------------------
    TARBALL="${SCRIPT_DIR}/pi-config-export.tar.gz"
    tar -czf "${TARBALL}" -C "${SCRIPT_DIR}" "$(basename "${EXPORT_DIR}")"
    ok "Created tarball: ${TARBALL}"
    TAR_SIZE=$(du -h "${TARBALL}" | cut -f1)
    info "Size: ${TAR_SIZE}"

    echo ""
    info "╔══════════════════════════════════════════════════════════════╗"
    info "║  EXPORT COMPLETE                                           ║"
    info "║                                                            ║"
    info "║  NEXT STEP for the LLM:                                    ║"
    info "║  1. Copy this tarball to the TARGET device.                ║"
    info "║     Example:                                               ║"
    info "║       scp ${TARBALL} user@target:~                            ║"
    info "║                                                            ║"
    info "║  2. On the target, run:                                    ║"
    info "║       ./scripts/pi-sync.sh import <path-to-tarball>         ║"
    info "╚══════════════════════════════════════════════════════════════╝"
    echo ""
}

# ===========================================================================
# PHASE 2 — IMPORT (run on the TARGET device)
#
# Reads the tarball produced by the export phase and:
#   1. Installs settings.json into ~/.pi/agent/settings.json
#   2. Installs theme files into ~/.pi/agent/themes/
#   3. Installs each package via `pi install`
#
# BACKUP: The existing ~/.pi/agent/ config is backed up with a timestamp
# before any changes are made, so you can always roll back.
# ===========================================================================
do_import() {
    TARBALL="$1"

    echo ""
    info "╔══════════════════════════════════════════════════════════════╗"
    info "║  pi-sync: IMPORT phase — run this on the TARGET device     ║"
    info "╚══════════════════════════════════════════════════════════════╝"
    echo ""

    # -- Validate tarball ---------------------------------------------------
    if [ ! -f "${TARBALL}" ]; then
        err "Tarball not found: ${TARBALL}"
        err "Usage: $0 import <path-to-pi-config-export.tar.gz>"
        exit 1
    fi
    ok "Found tarball: ${TARBALL} ($(du -h "${TARBALL}" | cut -f1))"

    # -- Extract to a temp directory ----------------------------------------
    TEMP_DIR=$(mktemp -d)
    trap 'rm -rf "${TEMP_DIR}"' EXIT
    tar -xzf "${TARBALL}" -C "${TEMP_DIR}"
    EXTRACTED_DIR=$(find "${TEMP_DIR}" -type d -name 'pi-config-export' | head -1)

    if [ -z "${EXTRACTED_DIR}" ]; then
        err "Could not find pi-config-export/ inside the tarball"
        err "Did you use the right tarball?"
        exit 1
    fi
    ok "Extracted to ${EXTRACTED_DIR}"

    # -- Validate extracted contents ----------------------------------------
    echo "  Contents:"
    for f in "${EXTRACTED_DIR}"/*; do
        echo "    $(basename "$f")"
    done

    # -- Backup existing ~/.pi/agent (if any) -------------------------------
    if [ -d "${PI_AGENT_DIR}" ]; then
        BACKUP_DIR="${PI_AGENT_DIR}.bak.$(date +%Y%m%d-%H%M%S)"
        cp -r "${PI_AGENT_DIR}" "${BACKUP_DIR}"
        ok "Backed up existing config to ${BACKUP_DIR}"
        info "  Rollback: rm -rf ~/.pi/agent && mv ${BACKUP_DIR} ~/.pi/agent"
    else
        mkdir -p "${PI_AGENT_DIR}"
        warn "No existing ~/.pi/agent/ — starting fresh"
    fi

    # -- Install settings.json ----------------------------------------------
    if [ -f "${EXTRACTED_DIR}/settings.json" ]; then
        mkdir -p "${PI_AGENT_DIR}"
        cp "${EXTRACTED_DIR}/settings.json" "${PI_AGENT_DIR}/settings.json"
        ok "Installed settings.json"

        # Show key settings for verification
        echo ""
        info "  Settings preview:"
        node -e "
            const s = require('${PI_AGENT_DIR}/settings.json');
            console.log('    theme:       ' + (s.theme || '(default)'));
            console.log('    provider:    ' + (s.defaultProvider || '(not set)'));
            console.log('    model:       ' + (s.defaultModel || '(not set)'));
            console.log('    thinking:    ' + (s.defaultThinkingLevel || '(default)'));
            console.log('    packages:    ' + ((s.packages || []).length + ' installed'));
        "
    else
        warn "No settings.json in export — skipping"
    fi

    # -- Install themes -----------------------------------------------------
    if [ -d "${EXTRACTED_DIR}/themes" ] && [ "$(ls -A "${EXTRACTED_DIR}/themes" 2>/dev/null)" ]; then
        mkdir -p "${PI_AGENT_DIR}/themes"
        cp "${EXTRACTED_DIR}/themes/"*.json "${PI_AGENT_DIR}/themes/"
        ok "Installed theme(s):"
        for f in "${EXTRACTED_DIR}/themes/"*.json; do
            echo "      $(basename "$f")"
        done
    else
        warn "No themes in export — skipping"
    fi

    # -- Install packages ---------------------------------------------------
    if [ -f "${EXTRACTED_DIR}/packages.txt" ] && [ -s "${EXTRACTED_DIR}/packages.txt" ]; then
        echo ""
        info "Installing $(wc -l < "${EXTRACTED_DIR}/packages.txt") package(s)..."
        echo ""
        while IFS= read -r pkg; do
            [ -z "${pkg}" ] && continue
            info "  pi install ${pkg}"
            # Run pi install — it will fetch from npm/git as needed
            if npx --yes pi install "${pkg}" 2>&1 | sed 's/^/    /'; then
                ok "Installed: ${pkg}"
            else
                warn "Failed to install: ${pkg} (may need manual setup)"
            fi
            echo ""
        done < "${EXTRACTED_DIR}/packages.txt"
    else
        warn "No packages.txt or it's empty — skipping package install"
        info "  You can manually install packages later with: pi install <name>"
    fi

    echo ""
    info "╔══════════════════════════════════════════════════════════════╗"
    info "║  IMPORT COMPLETE                                           ║"
    info "║                                                            ║"
    info "║  1. Launch pi on this device:                              ║"
    info "║       pi                                                    ║"
    info "║                                                            ║"
    info "║  2. The lotek theme (and any others) should be active.     ║"
    info "║     If not, check /settings in pi and select it.           ║"
    info "║                                                            ║"
    info "║  3. Verify packages with:                                  ║"
    info "║       pi list                                              ║"
    info "║                                                            ║"
    info "║  4. Rollback if something broke:                           ║"
    info "║     rm -rf ~/.pi/agent && mv ${BACKUP_DIR} ~/.pi/agent   ║"
    info "╚══════════════════════════════════════════════════════════════╝"
    echo ""
}

# ===========================================================================
# USAGE / HELP
# ===========================================================================
print_usage() {
    local SCRIPT
    SCRIPT=$(basename "$0")
    cat << EOF

╔══════════════════════════════════════════════════════════════════════╗
║  pi-sync.sh — Bootstrap pi settings, themes, and packages          ║
║                                                                    ║
║  An LLM-friendly script that handles the full lifecycle of syncing ║
║  your pi configuration from one device to another.                 ║
║                                                                    ║
║  LLM INSTRUCTIONS:                                                 ║
║                                                                    ║
║  1. First, identify which device is the SOURCE (has your config)   ║
║     and which is the TARGET (fresh device needing config).         ║
║                                                                    ║
║  2. On the SOURCE, run: ./scripts/pi-sync.sh export                ║
║     → This creates scripts/pi-config-export.tar.gz                 ║
║                                                                    ║
║  3. Transfer the tarball to the TARGET (scp, rsync, USB, etc.)    ║
║                                                                    ║
║  4. On the TARGET, run: ./scripts/pi-sync.sh import <path>         ║
║     → This backs up existing config, installs settings, themes,    ║
║       and packages.                                                ║
║                                                                    ║
║  5. Launch pi on the TARGET and verify everything works.           ║
╚══════════════════════════════════════════════════════════════════════╝

USAGE:
  ${SCRIPT} export
      Package current pi config (settings, themes, packages) into a tarball.

  ${SCRIPT} import <tarball-path>
      Unpack a previously exported tarball and install config on this device.

EXAMPLE:
  # On the old phone (source):
  ./scripts/pi-sync.sh export
  scp scripts/pi-config-export.tar.gz user@new-device:~

  # On the new device (target):
  ./scripts/pi-sync.sh import ~/pi-config-export.tar.gz

EOF
}

# ===========================================================================
# MAIN
# ===========================================================================
case "${1:-help}" in
    export)
        do_export
        ;;
    import)
        if [ -z "${2:-}" ]; then
            err "Missing path to tarball"
            echo "  Usage: $0 import <path-to-pi-config-export.tar.gz>"
            exit 1
        fi
        do_import "$2"
        ;;
    help|--help|-h|"")
        print_usage
        ;;
    *)
        err "Unknown command: $1"
        echo "  Usage: $0 export | import <tarball>"
        exit 1
        ;;
esac
